name: Deploy to Railway

on: [push, pull_request]

jobs:

  package:
    name: Maven Package (no tests)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  test:
    name: Maven Tests
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      # Adding a step to display the Maven version and settings for debugging
      - name: Display Maven Version and Settings
        run: |
          mvn -v
          mvn help:effective-settings

      # Run Maven verify with detailed logging
      - name: Maven Verify
        run: mvn -B clean verify -DtrimStackTrace=false -X

      # If you want to keep the test reports
      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/*.xml
