name: Deploy to Railway

on: [push, pull_request]

jobs:

  package:
    name: Maven Package (no tests)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  test:
    name: Maven Tests
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run Tests
        run: mvn -B test

  deploy:
    name: Railway Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: devtomio/action-railway@v1.1.4
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
